CREATE TABLE words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(50) NOT NULL,
    language VARCHAR(5) NOT NULL,
    length INTEGER NOT NULL,
    category VARCHAR(30),
    difficulty_level VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);-- index value & language
CREATE UNIQUE INDEX uk_word_language ON words (content, language);

-- indexes for frequently used fields
CREATE INDEX idx_word_length ON words (length);
CREATE INDEX idx_word_category ON words (category);

-- composite index
CREATE INDEX idx_word_language_category ON words (language, category);
CREATE INDEX idx_word_active_language ON words (is_active, language);